version: '3.7'
services:
  db:
    image: mongo:4
    restart: always
    volumes:
      - ./docker-data/db:/data/db
    ports:
      - 27018:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  api:
    # TODO: wait for mongodb to be available...
    image: entropychat.api
    build: .
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app:cached
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_ROOT_USER: ${MONGO_ROOT_USER}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
